name: mod_layout_one
description: A flexible and customizable layout package for Flutter applications with built-in theme and language support.
version: 0.0.1
homepage: https://github.com/yourusername/mod_layout_one

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

