name: mod_layout_one
description: A comprehensive Flutter layout package with theming and i18n support
version: 1.0.83
homepage: https://github.com/cesarmod2017/mod_layout_one
#proxima sera 1.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/

