name: mod_layout_one
description: A comprehensive Flutter layout package with theming and i18n support
version: 1.0.20
homepage: https://github.com/cesarmod2017/mod_layout_one

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.15
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/

